# Form implementation generated from reading ui file '.\\templates\\dlgTipoProp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GestiontipoProp(object):
    def setupUi(self, GestiontipoProp):
        GestiontipoProp.setObjectName("GestiontipoProp")
        GestiontipoProp.resize(400, 300)
        GestiontipoProp.setMinimumSize(QtCore.QSize(400, 300))
        GestiontipoProp.setMaximumSize(QtCore.QSize(400, 300))
        GestiontipoProp.setModal(True)
        self.frame = QtWidgets.QFrame(parent=GestiontipoProp)
        self.frame.setGeometry(QtCore.QRect(10, 50, 382, 171))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.txtGestTipoProp = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestTipoProp.setGeometry(QtCore.QRect(110, 120, 150, 20))
        self.txtGestTipoProp.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setObjectName("txtGestTipoProp")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 70, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 50, 50))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/house.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(parent=GestiontipoProp)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 381, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltaTipoProp.setMinimumSize(QtCore.QSize(80, 20))
        self.btnAltaTipoProp.setMaximumSize(QtCore.QSize(80, 20))
        self.btnAltaTipoProp.setObjectName("btnAltaTipoProp")
        self.horizontalLayout.addWidget(self.btnAltaTipoProp)
        self.btnEliminarTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnEliminarTipoProp.setMinimumSize(QtCore.QSize(80, 20))
        self.btnEliminarTipoProp.setMaximumSize(QtCore.QSize(80, 20))
        self.btnEliminarTipoProp.setObjectName("btnEliminarTipoProp")
        self.horizontalLayout.addWidget(self.btnEliminarTipoProp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(GestiontipoProp)
        QtCore.QMetaObject.connectSlotsByName(GestiontipoProp)

    def retranslateUi(self, GestiontipoProp):
        _translate = QtCore.QCoreApplication.translate
        GestiontipoProp.setWindowTitle(_translate("GestiontipoProp", "Dialog"))
        self.label.setText(_translate("GestiontipoProp", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaTipoProp.setText(_translate("GestiontipoProp", "Añadir"))
        self.btnEliminarTipoProp.setText(_translate("GestiontipoProp", "Eliminar"))
